import { reactive } from 'vue'
import { api, type DocumentItem } from './api'
export type UploadTask={key:string;file?:File;name:string;path:string;state:'queued'|'transferring'|'processing'|'ready'|'failed'|'skipped';progress:number;documentId?:string;error?:string;startedAt?:number;pollFailures?:number}
export function createUploadQueue(user:()=>string,onChange:()=>void,limits:()=>{allowed:string[];max:number;warning:number}){
  const state=reactive({open:false,paused:false,tasks:[] as UploadTask[],running:0})
  const pump=async()=>{while(!state.paused&&state.running<2){const task=state.tasks.find(x=>x.state==='queued');if(!task||!task.file)return;state.running++;task.state='transferring';void api.upload(user(),task.file,n=>task.progress=n).then(doc=>{task.documentId=doc.id;task.file=undefined;task.state='processing';poll(task)}).catch(e=>{task.state='failed';task.error=e.message}).finally(()=>{if(task.state!=='processing')state.running--;onChange();pump()})}}
  const poll=async(task:UploadTask)=>{try{const doc=await api.document(user(),task.documentId!);task.pollFailures=0;if(doc.status==='ready'||doc.status==='failed'){task.state=doc.status;task.error=doc.error_message||undefined;state.running--;onChange();pump();return}}catch(e:any){task.error=e.message;task.pollFailures=(task.pollFailures||0)+1;if(task.pollFailures>=3)state.paused=true}if(Date.now()-(task.startedAt||Date.now())>limits().warning*1000){task.error='处理时间较长，可继续等待';state.paused=true}setTimeout(()=>poll(task),state.paused?10000:5000)}
  return {state,add(files:FileList|null){if(!files)return;const config=limits();for(const file of Array.from(files)){const ext='.'+(file.name.split('.').pop()||'').toLowerCase(),invalid=!config.allowed.includes(ext)?'不支持此文件格式':file.size===0?'文件为空':file.size>config.max?'文件超过大小限制':'';state.tasks.push({key:crypto.randomUUID(),file:invalid?undefined:file,name:file.name,path:(file as any).webkitRelativePath||file.name,state:invalid?'failed':'queued',progress:0,error:invalid||undefined})}state.open=true;pump()},recover(items:DocumentItem[]){for(const doc of items.filter(x=>x.status==='processing'&&!state.tasks.some(t=>t.documentId===x.id))){const task:UploadTask={key:crypto.randomUUID(),name:doc.original_name,path:doc.original_name,state:'processing',progress:1,documentId:doc.id,startedAt:Date.now()};state.tasks.push(task);state.running++;poll(task)}},stop(){state.paused=true;state.tasks.filter(x=>x.state==='queued').forEach(x=>{x.state='skipped';x.file=undefined})},resume(){state.paused=false;state.tasks.forEach(x=>x.pollFailures=0);pump()}}
}
