<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue';import { useRoute,useRouter } from 'vue-router';import { Plus,Search,Send,Paperclip,ChevronRight,X,Sparkles,Database,Zap,LocateFixed } from 'lucide-vue-next'
import { useAppStore } from '../store';import { api,type Citation } from '../api';import MessageContent from '../components/MessageContent.vue'
const store=useAppStore(),route=useRoute(),router=useRouter(),draft=ref(''),mode=ref<'auto'|'knowledge'|'web'>('auto'),provider=ref('deepseek'),search=ref(''),citation=ref<Citation|null>(null),citationBody=ref<HTMLElement|null>(null),messageList=ref<HTMLElement|null>(null),picker=ref(false),estimate=ref<any>(null),timer=ref<number>()
const sessionId=computed(()=>route.params.sessionId as string|undefined),lastMetrics=computed(()=>[...store.messages].reverse().find(x=>x.role==='assistant'&&x.run_metadata?.metrics)?.run_metadata.metrics),webAvailable=computed(()=>store.capabilities?.web_search_enabled===true)
onMounted(()=>sessionId.value&&store.loadSession(sessionId.value));watch(sessionId,id=>id?store.loadSession(id as string):(store.currentSession=null,store.messages=[]))
watch(webAvailable,available=>{if(!available&&mode.value==='web')mode.value='auto'})
watch(()=>store.messages.at(-1)?.content,async()=>{if(store.busy){await nextTick();messageList.value?.scrollTo({top:messageList.value.scrollHeight})}})
watch([draft,mode,provider,sessionId],()=>{clearTimeout(timer.value);timer.value=window.setTimeout(async()=>{try{estimate.value=await api.estimate(store.userId,{session_id:sessionId.value||null,question:draft.value,model_provider:provider.value,search_mode:mode.value,document_ids:mode.value==='web'?undefined:(store.selectedDocuments.length?store.selectedDocuments:undefined)})}catch{estimate.value=null}},350)},{immediate:true})
async function submit(){if(!draft.value.trim()||store.busy)return;let id=sessionId.value;if(!id){const s=await store.createSession(draft.value.slice(0,24));if(!s)return;id=s.id;await router.replace(`/chat/${id}`)}const question=draft.value;draft.value='';await store.send(id,{question,search_mode:mode.value,model_provider:provider.value,document_ids:mode.value==='web'?undefined:(store.selectedDocuments.length?store.selectedDocuments:undefined)})}
async function compact(){if(sessionId.value&&estimate.value?.context_version){await api.compact(store.userId,sessionId.value,estimate.value.context_version,provider.value);await store.loadSession(sessionId.value)}}
async function openCitation(value:Citation){citation.value=value;await nextTick();citationBody.value?.scrollTo({top:0})}
async function locateCitation(){if(!citation.value)return;const number=citation.value.number;citation.value=null;await nextTick();const target=document.querySelector<HTMLElement>(`.citation-ref[data-citation="${number}"]`);target?.scrollIntoView({behavior:'smooth',block:'center'});target?.focus();target?.classList.add('located');window.setTimeout(()=>target?.classList.remove('located'),1600)}
</script>
<template><div class="chat-layout"><aside class="sessions"><button class="new-chat" @click="router.push('/chat')"><Plus/>新建对话</button><label class="search"><Search/><input v-model="search" placeholder="搜索对话" @input="store.loadSessions(search)"/></label><div class="session-list"><RouterLink v-for="s in store.sessions" :key="s.id" :to="`/chat/${s.id}`"><span>{{s.title}}</span><small>{{new Date(s.updated_at).toLocaleDateString()}}</small></RouterLink></div></aside>
<section class="conversation"><header class="chat-head"><div><small>KNOWLEDGE WORKSPACE</small><h1>{{store.currentSession?.title||'与资料开始一场对话'}}</h1></div><div class="head-controls"><select v-model="provider"><option v-for="m in store.capabilities?.models.filter(x=>x.available)" :value="m.provider">{{m.model_name}}</option></select><button class="ghost" @click="picker=true"><Paperclip/>{{store.selectedDocuments.length?`${store.selectedDocuments.length} 项资料`:'全部资料'}}</button></div></header>
<div ref="messageList" class="messages" :class="{empty:!store.messages.length}"><div v-if="!store.messages.length" class="welcome"><div class="orb"><Sparkles/></div><small>资料会成为回答的依据</small><h2>今天想弄清楚什么？</h2><p>上传项目文档、表格或演示稿，然后让 Learning Q&A 替你检索、梳理和引用。</p><div><button @click="draft='总结当前资料的核心内容'">总结资料</button><button @click="draft='找出资料中相互矛盾的观点'">检查矛盾</button></div></div>
<article v-for="m in store.messages" :key="m.id" :class="['message',m.role]"><div class="role">{{m.role==='user'?'你':'Learning Q&A'}}</div><MessageContent :content="m.content" :citations="m.citations||[]" :active-citation="citation?.number" @citation="openCitation"/><div v-if="m.role==='assistant'&&m.model_name" class="message-meta">{{m.model_name}} · {{m.token_usage?.total_tokens??'—'}} tokens</div></article><div v-if="store.busy" class="thinking"><i/><i/><i/> {{store.streamStatus||'正在梳理资料'}}</div></div>
<footer class="composer"><div class="mode-tabs"><button v-for="m in ['auto','knowledge','web']" :class="{active:mode===m}" :disabled="m==='web'&&!webAvailable" :title="m==='web'&&!webAvailable?'联网搜索尚未启用':undefined" @click="mode=m as any">{{{auto:'自动',knowledge:'知识库',web:'联网'}[m]}}</button></div><textarea v-model="draft" maxlength="8000" placeholder="输入问题，Enter 发送，Shift + Enter 换行" @keydown.enter.exact.prevent="submit"/><button class="send" :disabled="!draft.trim()||store.busy" @click="submit"><Send/></button><div class="usage"><div><Database/>缓存命中 <strong>{{lastMetrics?.cache?.by_model?.[0]?.hit_rate!=null?Math.round(lastMetrics.cache.by_model[0].hit_rate*100)+'%':'—'}}</strong></div><div><Zap/>预计上下文 <strong>{{estimate?`${Math.round(estimate.usage_ratio*100)}%`:'—'}}</strong><button v-if="estimate?.recommendation?.includes('compaction')&&sessionId" @click="compact">压缩</button></div></div></footer></section>
<div v-if="picker" class="modal-mask" @click.self="picker=false"><div class="modal"><header><h3>选择资料</h3><button class="icon" @click="picker=false"><X/></button></header><label v-for="d in store.readyDocuments"><input v-model="store.selectedDocuments" type="checkbox" :value="d.id"/>{{d.original_name}}</label><button class="primary" @click="picker=false">完成</button></div></div>
<aside v-if="citation" class="citation-panel" role="dialog" :aria-label="`引用 ${citation.number}`"><header><small>引用 {{citation.number}}</small><button class="icon" aria-label="关闭引用" @click="citation=null"><X/></button></header><div class="citation-heading"><h3>{{citation.source_name||citation.title}}</h3><p>{{citation.section||citation.page_number&&`第 ${citation.page_number} 页`}}</p></div><div ref="citationBody" class="citation-scroll"><p class="citation-location">高亮引用片段</p><blockquote><mark>{{citation.excerpt}}</mark></blockquote></div><footer><button class="ghost" @click="locateCitation"><LocateFixed/>定位回答中的引用</button><a v-if="citation.url" :href="citation.url" target="_blank" rel="noopener noreferrer">查看网页 <ChevronRight/></a></footer></aside>
</div></template>
