<script setup lang="ts">
import { onMounted,ref,watch } from 'vue';import { Search,Upload,FolderUp,Trash2,RefreshCw,FileText } from 'lucide-vue-next';import { useAppStore } from '../store'
const store=useAppStore(),q=ref(''),status=ref(''),selected=ref<string[]>([]),fileInput=ref<HTMLInputElement>(),folderInput=ref<HTMLInputElement>(),timer=ref<number>()
onMounted(()=>store.loadDocuments());watch([q,status],()=>{clearTimeout(timer.value);timer.value=window.setTimeout(()=>{selected.value=[];store.loadDocuments(q.value,status.value)},300)})
function choose(input:HTMLInputElement|undefined){input?.click()}function add(e:Event){store.uploads.add((e.target as HTMLInputElement).files);(e.target as HTMLInputElement).value=''}
async function remove(){if(!selected.value.length||!confirm(`确定删除选中的 ${selected.value.length} 项资料？`))return;await store.removeDocuments(selected.value);selected.value=[]}
const stateLabel=(s:string)=>s==='ready'?'上传成功':s==='failed'?'上传失败':'上传中'
</script>
<template><section class="documents"><header class="page-title"><div><small>KNOWLEDGE LIBRARY</small><h1>资料</h1><p>把散落的文件收进同一处，让每次回答都有迹可循。</p></div><div><button class="secondary" @click="choose(folderInput)"><FolderUp/>上传文件夹</button><button class="primary" @click="choose(fileInput)"><Upload/>上传文件</button></div></header>
<input ref="fileInput" hidden type="file" multiple @change="add"><input ref="folderInput" hidden type="file" multiple webkitdirectory @change="add">
<div class="library-bar"><label class="search"><Search/><input v-model="q" placeholder="搜索全部已上传文件"/></label><select v-model="status"><option value="">全部状态</option><option value="ready">上传成功</option><option value="processing">上传中</option><option value="failed">上传失败</option></select><span>{{store.documentTotal}} 项资料</span><button v-if="selected.length" class="danger" @click="remove"><Trash2/>删除 {{selected.length}} 项</button></div>
<div class="table-wrap"><table><thead><tr><th></th><th>文件</th><th>状态</th><th>大小</th><th>更新时间</th><th></th></tr></thead><tbody><tr v-for="d in store.documents" :key="d.id"><td><input v-model="selected" type="checkbox" :value="d.id"></td><td><div class="file-cell"><span><FileText/></span><div><strong>{{d.original_name}}</strong><small>{{d.file_type.replace('.','').toUpperCase()}} · {{d.chunk_count}} 个片段</small></div></div></td><td><span :class="['status',d.status]">{{stateLabel(d.status)}}</span><small v-if="!d.can_query&&d.status==='ready'">需要重新入库</small></td><td>{{d.size_bytes==null?'—':(d.size_bytes/1024/1024).toFixed(1)+' MB'}}</td><td>{{new Date(d.updated_at).toLocaleString()}}</td><td><button v-if="d.status==='failed'" class="icon" aria-label="重试" @click="store.retryDocument(d.id)"><RefreshCw/></button></td></tr><tr v-if="!store.documents.length"><td colspan="6" class="empty-row">没有找到资料</td></tr></tbody></table></div>
</section></template>
